const BlogData = [
  {
    id: 1,
    date: "12 Ocak, 2024",
    catgeory: "Lüks ",
    title: "Şık ve Konforlu Odalar",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Misafirlerimiz için her detayın özenle düşünüldüğü şık bir konaklama ortamı sağlıyoruz.",
    desc: "Her odada konfor ve şıklık bir arada! Modern tasarımlar, kaliteli mobilyalar ve göz alıcı dekorasyon ile rahatça dinlenebileceğiniz bir ortam sağlanmış. Yumuşacık yataklar ve lüks banyo olanaklarıyla, evinizdeymiş gibi hissedeceğiniz bir konaklama deneyimi sizi bekliyor.",
  },
  {
    id: 2,
    date: "22 Nisan, 2021",
    catgeory: "Zarafet",
    title: "Eşsiz Manzaralı Odalar",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Güler yüzlü personelimiz ve kaliteli hizmet anlayışımızla kendinizi evinizde gibi hissedeceksiniz.",
    desc: "Bu otelin odaları sadece konforlu değil, aynı zamanda harika manzaralar sunuyor. Odanızdan, şehri ya da denizi izlerken sabah kahvenizi içmenin keyfi bir başka olacak. Geniş pencereler, doğal ışık ve rahatlatıcı atmosferle mükemmel bir dinlenme ortamı sağlıyor.",
  },
  {
    id: 3,
    date: "9 Mayıs, 2018",
    catgeory: "Dinlenme",
    title: "Zarif ve Fonksiyonel Tasarımlar",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Eşsiz manzaraları ve konforlu odalarıyla unutulmaz bir tatil deneyimi sunuyoruz.",
    desc: "Odalar, zarif tasarımları ve işlevsel düzenlemeleriyle dikkat çekiyor. Her şeyin elinizin altında olduğu, ferah ve düzenli odalar, tatilinizi daha keyifli hale getirecek. Otelde geçirdiğiniz her an, size huzur ve rahatlık sunuyor.",
  },
  {
    id: 4,
    date: "24 Ağustos, 2019",
    catgeory: " Misafirperverlik",
    title: "Smart Flexible Visiting Card",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Lüks ve modern tasarımlarıyla otelimiz, tatilinize zarafet katıyor.",
    desc: "Bu otelin odaları sadece konforlu değil, aynı zamanda harika manzaralar sunuyor. Odanızdan, şehri ya da denizi izlerken sabah kahvenizi içmenin keyfi bir başka olacak. Geniş pencereler, doğal ışık ve rahatlatıcı atmosferle mükemmel bir dinlenme ortamı sağlıyor.",
  },
  {
    id: 5,
    date: "16 Eylül, 2022",
    catgeory: "Huzur",
    title: "Modern Teknolojiyle Donatılmış Odalar",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Her sabah taptaze ve lezzet dolu kahvaltılarla güne harika bir başlangıç yapabilirsiniz.",
    desc: "Bu otelde, her odada en son teknolojiye sahip cihazlar yer alıyor. Akıllı TV'ler, hızlı internet bağlantısı ve konforlu çalışma alanları sayesinde, tatilinizin keyfini çıkarırken işlerinizi de kolayca halledebilirsiniz. Odalar, modern yaşamın her ihtiyacına cevap veriyor.",
  },
  {
    id: 6,
    date: "12 Ekim, 2021",
    catgeory: "Şıklık",
    title: "Why you Should Always First",
    cover: "/images/singlepage/blog-6.jpg",
    para: "Dinlendirici spa hizmetlerimizle hem bedeninizi hem de ruhunuzu yenileyin.",
    desc: "Bu otelin odaları sadece konforlu değil, aynı zamanda harika manzaralar sunuyor. Odanızdan, şehri ya da denizi izlerken sabah kahvenizi içmenin keyfi bir başka olacak. Geniş pencereler, doğal ışık ve rahatlatıcı atmosferle mükemmel bir dinlenme ortamı sağlıyor.",
  },
  {
    id: 7,
    date: "22 Kasım, 2024",
    catgeory: "Özgünlük",
    title: "Lüks ve Özel Tasarlanmış Odalar",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Otelden adımınızı attığınız anda başlayan konfor ve huzur, tatil boyunca sizinle olacak",
    desc: "Bu otelde, her odada en son teknolojiye sahip cihazlar yer alıyor. Akıllı TV'ler, hızlı internet bağlantısı ve konforlu çalışma alanları sayesinde, tatilinizin keyfini çıkarırken işlerinizi de kolayca halledebilirsiniz. Odalar, modern yaşamın her ihtiyacına cevap veriyor.",
  },
  {
    id: 8,
    date: "17 Aralık, 2022",
    catgeory: " Motion Designer",
    title: "Rahatlatıcı ve Sakin Ortam",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Merkezi konumu sayesinde şehri keşfetmek ve eğlenceli aktivitelere katılmak çok kolay.",
    desc: "Her odada konfor ve şıklık bir arada! Modern tasarımlar, kaliteli mobilyalar ve göz alıcı dekorasyon ile rahatça dinlenebileceğiniz bir ortam sağlanmış. Yumuşacık yataklar ve lüks banyo olanaklarıyla, evinizdeymiş gibi hissedeceğiniz bir konaklama deneyimi sizi bekliyor.",
  },
  {
    id: 9,
    date: "30 Aralık, 2023",
    catgeory: "Kalite",
    title: "Rahatlatıcı ve Sakin Ortam",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Sunduğumuz premium hizmetlerle misafirlerimizin beklentilerinin ötesine geçiyoruz",
    desc: "Yalnızca estetik açıdan değil, huzur verici atmosferiyle de dikkat çeken odalar, tatilinizi mükemmel bir deneyime dönüştürüyor. Her odada sessiz bir ortam, kaliteli ses yalıtımı ve rahat bir uyku için gereken her şey düşünülmüş. Konaklamanız boyunca tüm stresinizi geride bırakabilirsiniz.",
  },
];

export default BlogData;
